import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ThemeProvider } from "./_components/theme-provide";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Ai Course Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (



    <html lang="en">
        <body className={inter.className} >
      <ClerkProvider
        appearance={{
          layout: {
            unsafe_disableDevelopmentModeWarnings: true,
          },
        }}
      >
        <GoogleOneTap />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
        <Toaster position="top-right" richColors />
          </ThemeProvider>
      </ClerkProvider>
        </body>
    </html>
  );
}
